# Playing with Dataset

In [2]:
import xml.etree.ElementTree as ET
import pandas as pd

def xml_to_rows(xml_file):
    tree = ET.parse(xml_file)
    root = tree.getroot()

    rows = []

    for sentence in root.findall("sentence"):
        sid = sentence.get("id")
        text = sentence.find("text").text

        aspect_terms = sentence.find("aspectTerms")

        if aspect_terms is not None:
            for aspect in aspect_terms.findall("aspectTerm"):
                rows.append({
                    "id": sid,
                    "sentence": text,
                    "aspect": aspect.get("term"),
                    "polarity": aspect.get("polarity")
                })

    return pd.DataFrame(rows)

In [10]:
myXML = xml_to_rows("./Restaurants_Train_v2.xml")

In [24]:
myXML.shape

(3693, 4)

In [11]:
myXML.head()

     id                                           sentence   aspect  polarity
0  3121               But the staff was so horrible to us.    staff  negative
1  2777  To be completely fair, the only redeeming fact...     food  positive
2  1634  The food is uniformly exceptional, with a very...     food  positive
3  1634  The food is uniformly exceptional, with a very...  kitchen  positive
4  1634  The food is uniformly exceptional, with a very...     menu   neutral

In [16]:
import pandas as pd

csv_df = pd.read_csv("./Laptop_Train_v2.csv", encoding="utf-8")

csv_df = csv_df[[
    "id",
    "Sentence",
    "Aspect Term",
    "polarity"
]]

csv_df.columns = ["id", "sentence", "aspect", "polarity"]

In [17]:
csv_df.head()

,id,sentence,aspect,polarity
0,2339,I charge it at night and skip taking the cord ...,cord,neutral
1,2339,I charge it at night and skip taking the cord ...,battery life,positive
2,1316,The tech guy then said the service center does...,service center,negative
3,1316,The tech guy then said the service center does...,"""sales"" team",negative
4,1316,The tech guy then said the service center does...,tech guy,neutral

In [25]:
csv_df.shape

(2358, 4)

# Merge the datasets

In [18]:
final_df = pd.concat([csv_df, myXML], ignore_index=True)

In [19]:
final_df.head()

,id,sentence,aspect,polarity
0,2339,I charge it at night and skip taking the cord ...,cord,neutral
1,2339,I charge it at night and skip taking the cord ...,battery life,positive
2,1316,The tech guy then said the service center does...,service center,negative
3,1316,The tech guy then said the service center does...,"""sales"" team",negative
4,1316,The tech guy then said the service center does...,tech guy,neutral

In [23]:
final_df.shape

(6051, 4)

In [26]:
2358+3693

6051